"""
Reporting Engine for Phase 4: Achievement Portfolio & Leadership Narratives.

Provides:
- Achievement portfolio generation (structured high-impact evidence)
- Multi-cycle trend data aggregation
"""

import logging
from typing import Dict

from src.domain.analysis import aggregate_achievements, calculate_burnout_risk
from src.utils.time_utils import utc_now_naive

_logger = logging.getLogger(__name__)


def generate_achievement_portfolio(
    user_id: int,
    cycle_id: int,
    user_display_name: str = "Team Member",
    effectiveness_threshold: float = 0.7,
) -> Dict:
    """
    Build a structured "Achievement Portfolio" for professional reviews.

    Returns a dict with:
      - user: display name
      - generated_at: ISO timestamp
      - cycle_id
      - total_achievements: count
      - total_high_impact_hours: float
      - achievements: list of achievement dicts
      - burnout_snapshot: current risk assessment
      - summary_text: narrative one-liner
    """
    achievements = aggregate_achievements(
        user_id=user_id,
        cycle_id=cycle_id,
        effectiveness_threshold=effectiveness_threshold,
    )

    total_high_impact_minutes = sum(a.get("time_spent", 0) for a in achievements)
    total_high_impact_hours = round(total_high_impact_minutes / 60, 1)

    burnout = calculate_burnout_risk(user_id, days=14)

    # Narrative summary
    if not achievements:
        summary = (
            f"{user_display_name} has no high-impact contributions recorded "
            f"for this cycle yet."
        )
    else:
        top_obj = achievements[0].get("objective_title", "—")
        summary = (
            f"{user_display_name} completed {len(achievements)} high-impact "
            f"task(s) totalling {total_high_impact_hours}h, with strongest "
            f'contribution toward "{top_obj}".'
        )

    return {
        "user": user_display_name,
        "generated_at": utc_now_naive().isoformat(),
        "cycle_id": cycle_id,
        "total_achievements": len(achievements),
        "total_high_impact_hours": total_high_impact_hours,
        "achievements": achievements,
        "burnout_snapshot": burnout,
        "summary_text": summary,
    }


def format_portfolio_as_markdown(portfolio: Dict) -> str:
    """Render an achievement portfolio as a printable Markdown document."""
    lines = [
        f"# Achievement Portfolio — {portfolio.get('user', 'User')}",
        "",
        f"**Generated**: {portfolio.get('generated_at', '')}  ",
        f"**Cycle**: {portfolio.get('cycle_id', '—')}  ",
        f"**High-Impact Contributions**: {portfolio.get('total_achievements', 0)}  ",
        f"**Total High-Impact Hours**: {portfolio.get('total_high_impact_hours', 0)}",
        "",
        "---",
        "",
        f"> {portfolio.get('summary_text', '')}",
        "",
    ]

    achievements = portfolio.get("achievements", [])
    if achievements:
        lines.append("## Contributions")
        lines.append("")
        lines.append("| Task | KR | Objective | Score | Time |")
        lines.append("|------|------|-----------|-------|------|")
        for a in achievements:
            time_h = round(a.get("time_spent", 0) / 60, 1)
            lines.append(
                f"| {a['task_title']} "
                f"| {a['kr_title']} "
                f"| {a['objective_title']} "
                f"| {a['kr_score']:.2f} ({a['kr_score_label']}) "
                f"| {time_h}h |"
            )
        lines.append("")

    burnout = portfolio.get("burnout_snapshot", {})
    if burnout:
        lines.append("## Health Snapshot")
        lines.append("")
        lines.append(
            f"- **Burnout Risk**: {burnout.get('risk_label', '—')} ({burnout.get('risk_score', 0)})"
        )
        lines.append(
            f"- **Avg Daily Focus**: {burnout.get('avg_daily_minutes', 0)} min"
        )
        lines.append(
            f"- **Tasks Completed (14d)**: {burnout.get('completed_tasks', 0)}"
        )
        lines.append("")

    lines.append("---")
    lines.append("_Generated by the OKR Strategy Engine._")

    return "\n".join(lines)
