// Flat ESLint config for the two JavaScript workspaces.
//
// Scope: the `lint` script passes both whole packages, so the ignores below —
// not a hand-maintained path list — decide what is skipped, and the only thing
// skipped is generated output. That covers the test trees, the tool config
// files (`next.config.ts`, both `vitest.config.ts`) and the Node helper scripts.
// An earlier revision listed only `spa-web/src` and `spa-bff/src`, which left
// six hand-written files ungated; that list is gone rather than extended, so a
// file added tomorrow is linted by default.
//
// Rule levels are measured, not guessed, and the evidence lives in the C4 rows
// of docs/REMAINING_ENGINEERING_PLAN.md. `no-explicit-any` and
// `no-floating-promises` are errors because the tree is clean of both, so
// enforcing them costs nothing. `no-unused-vars` and `exhaustive-deps` are
// warnings because they carry real, tracked findings that this config did not
// clear — they are deliberately visible rather than silently allowed.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

// TypeScript that belongs to a tsconfig project, so type-aware rules can run.
// Every path here must be inside a `tsconfig.json` `include`; `spa-bff/vitest.config.ts`
// is listed in that project's include for exactly this reason.
const TYPED_SOURCE = [
  "spa-web/**/*.ts",
  "spa-web/**/*.tsx",
  "spa-bff/**/*.ts",
];

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/.next/**",
      "**/dist/**",
      "**/coverage/**",
      "**/coverage-probe/**",
      "**/.vitest/**",
      "spa-web/src/lib/api/generated/**",
      "spa-bff/src/generated/**",
      // Regenerated by `next build`; not hand-written.
      "spa-web/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: TYPED_SOURCE,
    plugins: {
      "react-hooks": reactHooks,
    },
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-unused-vars": "warn",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  {
    // TypeScript resolves identifiers itself, so the base rule only produces
    // false positives on type positions and ambient globals.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-undef": "off",
    },
  },
  {
    // Node ESM helper scripts. These are the Node globals the scripts reference,
    // established by running the rule and closing every report until it was
    // clean, so `no-undef` stays switched on rather than being disabled
    // wholesale. A global outside this list surfaces as an error, which is the
    // safe direction: it is visible in CI and fixed by adding it here.
    files: ["spa-web/scripts/**/*.mjs", "spa-bff/scripts/**/*.mjs"],
    languageOptions: {
      globals: {
        process: "readonly",
        console: "readonly",
        URL: "readonly",
      },
    },
  },
];
