"""Initial 4-level schema

Revision ID: 9aa9ae459f5b
Revises: 
Create Date: 2026-02-03 10:32:27.101974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9aa9ae459f5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_strategy_external_id'), table_name='strategy')
    # op.drop_index(op.f('ix_strategy_goal_id'), table_name='strategy')
    # op.drop_index(op.f('ix_strategy_title'), table_name='strategy')
    # op.drop_table('strategy')
    # op.drop_index(op.f('ix_initiative_external_id'), table_name='initiative')
    # op.drop_index(op.f('ix_initiative_key_result_id'), table_name='initiative')
    # op.drop_index(op.f('ix_initiative_title'), table_name='initiative')
    # op.drop_table('initiative')
    op.drop_column('goal', 'initiative_tags')
    op.alter_column('key_result', 'initiative_tags',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('objective', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_objective_strategy_id'), table_name='objective')
    op.create_index(op.f('ix_objective_goal_id'), 'objective', ['goal_id'], unique=False)
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.create_foreign_key(None, 'objective', 'goal', ['goal_id'], ['id'])
    op.drop_column('objective', 'strategy_id')
    op.alter_column('task', 'key_result_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('task', 'deadline',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_task_initiative_id'), table_name='task')
    op.drop_index(op.f('ix_task_status_initiative'), table_name='task')
    op.create_index('ix_task_status_kr', 'task', ['status', 'key_result_id'], unique=False)
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'initiative_id')
    op.add_column('work_log', sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('work_log', 'duration_minutes',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_log', 'duration_minutes',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('work_log', 'summary')
    op.add_column('task', sa.Column('initiative_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'task', 'initiative', ['initiative_id'], ['id'])
    op.drop_index('ix_task_status_kr', table_name='task')
    op.create_index(op.f('ix_task_status_initiative'), 'task', ['status', 'initiative_id'], unique=False)
    op.create_index(op.f('ix_task_initiative_id'), 'task', ['initiative_id'], unique=False)
    op.alter_column('task', 'deadline',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('task', 'key_result_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('objective', sa.Column('strategy_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'objective', type_='foreignkey')
    op.create_foreign_key(None, 'objective', 'strategy', ['strategy_id'], ['id'])
    op.drop_index(op.f('ix_objective_goal_id'), table_name='objective')
    op.create_index(op.f('ix_objective_strategy_id'), 'objective', ['strategy_id'], unique=False)
    op.alter_column('objective', 'goal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('key_result', 'initiative_tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('goal', sa.Column('initiative_tags', sa.VARCHAR(), nullable=True))
    op.create_table('initiative',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_expanded', sa.BOOLEAN(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('deadline', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key_result_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['key_result_id'], ['key_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initiative_title'), 'initiative', ['title'], unique=False)
    op.create_index(op.f('ix_initiative_key_result_id'), 'initiative', ['key_result_id'], unique=False)
    op.create_index(op.f('ix_initiative_external_id'), 'initiative', ['external_id'], unique=False)
    op.create_table('strategy',
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('progress', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_expanded', sa.BOOLEAN(), nullable=False),
    sa.Column('external_id', sa.VARCHAR(), nullable=True),
    sa.Column('deadline', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('goal_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_title'), 'strategy', ['title'], unique=False)
    op.create_index(op.f('ix_strategy_goal_id'), 'strategy', ['goal_id'], unique=False)
    op.create_index(op.f('ix_strategy_external_id'), 'strategy', ['external_id'], unique=False)
    # ### end Alembic commands ###
