apiVersion: v1
kind: Secret
metadata:
  name: okr-db
  namespace: okr
stringData:
  OKR_DATABASE_URL: postgresql+psycopg2://postgres.PROJECT_REF:DB_PASSWORD@aws-0-REGION.pooler.supabase.com:5432/postgres?sslmode=require
