// AUTO-GENERATED by scripts/generate_bff_allowlist.py. Do not edit by hand.
// The literal entries below are required by tooling (e.g. the backend
// mutation auth-matrix test) that parses this file with regex.

export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
import type { BackendOperationId } from "./backend-schema.js";

export interface AllowlistRule {
  pathTemplate: string;
  methods: readonly HttpMethod[];
  pathRegex: RegExp;
  actorRequired: boolean;
  operationIds: Readonly<Partial<Record<HttpMethod, BackendOperationId>>>;
}

export const ALLOWLIST_POLICY_ROUTES: readonly AllowlistRule[] = [
  { pathTemplate: "/v1/admin/ai-health", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/ai-health$"), actorRequired: true, operationIds: {"GET": "api_admin_ai_health_v1_admin_ai_health_get"} },
  { pathTemplate: "/v1/admin/db-backup", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/db-backup$"), actorRequired: true, operationIds: {"GET": "api_admin_db_backup_v1_admin_db_backup_get"} },
  { pathTemplate: "/v1/admin/db-restore", methods: ["POST"], pathRegex: new RegExp("^/v1/admin/db-restore$"), actorRequired: true, operationIds: {"POST": "api_admin_db_restore_v1_admin_db_restore_post"} },
  { pathTemplate: "/v1/admin/pdf-health", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/pdf-health$"), actorRequired: true, operationIds: {"GET": "api_admin_pdf_health_v1_admin_pdf_health_get"} },
  { pathTemplate: "/v1/ai/analyze-node", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/analyze-node$"), actorRequired: true, operationIds: {"POST": "api_ai_analyze_node_v1_ai_analyze_node_post"} },
  { pathTemplate: "/v1/ai/strategy-pulse", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/strategy-pulse$"), actorRequired: true, operationIds: {"POST": "api_ai_strategy_pulse_v1_ai_strategy_pulse_post"} },
  { pathTemplate: "/v1/ai/team-coach", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/team-coach$"), actorRequired: true, operationIds: {"POST": "api_ai_team_coach_v1_ai_team_coach_post"} },
  { pathTemplate: "/v1/alignments", methods: ["POST"], pathRegex: new RegExp("^/v1/alignments$"), actorRequired: true, operationIds: {"POST": "api_create_alignment_v1_alignments_post"} },
  { pathTemplate: "/v1/alignments/{edge_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/alignments/\\d+$"), actorRequired: true, operationIds: {"DELETE": "api_delete_alignment_v1_alignments__edge_id__delete"} },
  { pathTemplate: "/v1/auth/login", methods: ["POST"], pathRegex: new RegExp("^/v1/auth/login$"), actorRequired: false, operationIds: {"POST": "api_auth_login_v1_auth_login_post"} },
  { pathTemplate: "/v1/auth/me", methods: ["GET"], pathRegex: new RegExp("^/v1/auth/me$"), actorRequired: true, operationIds: {"GET": "api_get_current_user_v1_auth_me_get"} },
  { pathTemplate: "/v1/check-ins", methods: ["POST"], pathRegex: new RegExp("^/v1/check-ins$"), actorRequired: true, operationIds: {"POST": "api_create_check_in_v1_check_ins_post"} },
  { pathTemplate: "/v1/cycles", methods: ["POST"], pathRegex: new RegExp("^/v1/cycles$"), actorRequired: true, operationIds: {"POST": "api_create_cycle_v1_cycles_post"} },
  { pathTemplate: "/v1/cycles/{cycle_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/cycles/\\d+$"), actorRequired: true, operationIds: {"PATCH": "api_update_cycle_v1_cycles__cycle_id__patch", "DELETE": "api_delete_cycle_v1_cycles__cycle_id__delete"} },
  { pathTemplate: "/v1/experiments", methods: ["POST"], pathRegex: new RegExp("^/v1/experiments$"), actorRequired: true, operationIds: {"POST": "api_create_experiment_v1_experiments_post"} },
  { pathTemplate: "/v1/experiments/{experiment_id}", methods: ["PATCH"], pathRegex: new RegExp("^/v1/experiments/\\d+$"), actorRequired: true, operationIds: {"PATCH": "api_update_experiment_v1_experiments__experiment_id__patch"} },
  { pathTemplate: "/v1/experiments/{experiment_id}/close", methods: ["POST"], pathRegex: new RegExp("^/v1/experiments/\\d+/close$"), actorRequired: true, operationIds: {"POST": "api_close_experiment_v1_experiments__experiment_id__close_post"} },
  { pathTemplate: "/v1/jobs", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs$"), actorRequired: true, operationIds: {"POST": "api_submit_job_v1_jobs_post"} },
  { pathTemplate: "/v1/jobs/dead", methods: ["GET"], pathRegex: new RegExp("^/v1/jobs/dead$"), actorRequired: true, operationIds: {"GET": "api_list_dead_jobs_v1_jobs_dead_get"} },
  { pathTemplate: "/v1/jobs/{job_id}", methods: ["GET", "DELETE"], pathRegex: new RegExp("^/v1/jobs/[^/]+$"), actorRequired: true, operationIds: {"GET": "api_get_job_v1_jobs__job_id__get", "DELETE": "api_delete_job_v1_jobs__job_id__delete"} },
  { pathTemplate: "/v1/jobs/{job_id}/cancel", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs/[^/]+/cancel$"), actorRequired: true, operationIds: {"POST": "api_cancel_job_v1_jobs__job_id__cancel_post"} },
  { pathTemplate: "/v1/jobs/{job_id}/retry", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs/[^/]+/retry$"), actorRequired: true, operationIds: {"POST": "api_retry_dead_job_v1_jobs__job_id__retry_post"} },
  { pathTemplate: "/v1/nodes/goal", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/goal$"), actorRequired: true, operationIds: {"POST": "api_create_goal_v1_nodes_goal_post"} },
  { pathTemplate: "/v1/nodes/key_result", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/key_result$"), actorRequired: true, operationIds: {"POST": "api_create_key_result_v1_nodes_key_result_post"} },
  { pathTemplate: "/v1/nodes/objective", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/objective$"), actorRequired: true, operationIds: {"POST": "api_create_objective_v1_nodes_objective_post"} },
  { pathTemplate: "/v1/nodes/task", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/task$"), actorRequired: true, operationIds: {"POST": "api_create_task_v1_nodes_task_post"} },
  { pathTemplate: "/v1/nodes/{node_type}/{node_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/nodes/[a-zA-Z_]+/\\d+$"), actorRequired: true, operationIds: {"PATCH": "api_update_node_v1_nodes__node_type___node_id__patch", "DELETE": "api_delete_node_v1_nodes__node_type___node_id__delete"} },
  { pathTemplate: "/v1/objective-alignment-links", methods: ["POST"], pathRegex: new RegExp("^/v1/objective-alignment-links$"), actorRequired: true, operationIds: {"POST": "api_create_objective_alignment_link_v1_objective_alignment_links_post"} },
  { pathTemplate: "/v1/objective-alignment-links/{link_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/objective-alignment-links/\\d+$"), actorRequired: true, operationIds: {"DELETE": "api_delete_objective_alignment_link_v1_objective_alignment_links__link_id__delete"} },
  { pathTemplate: "/v1/read/atlas/snapshot", methods: ["POST"], pathRegex: new RegExp("^/v1/read/atlas/snapshot$"), actorRequired: true, operationIds: {"POST": "api_read_atlas_snapshot_v1_read_atlas_snapshot_post"} },
  { pathTemplate: "/v1/read/leadership/metrics", methods: ["POST"], pathRegex: new RegExp("^/v1/read/leadership/metrics$"), actorRequired: true, operationIds: {"POST": "api_read_leadership_metrics_v1_read_leadership_metrics_post"} },
  { pathTemplate: "/v1/read/query", methods: ["POST"], pathRegex: new RegExp("^/v1/read/query$"), actorRequired: true, operationIds: {"POST": "api_read_query_v1_read_query_post"} },
  { pathTemplate: "/v1/retrospectives", methods: ["POST"], pathRegex: new RegExp("^/v1/retrospectives$"), actorRequired: true, operationIds: {"POST": "api_create_retrospective_v1_retrospectives_post"} },
  { pathTemplate: "/v1/retrospectives/{retrospective_id}/experiment-outcomes", methods: ["PUT"], pathRegex: new RegExp("^/v1/retrospectives/\\d+/experiment-outcomes$"), actorRequired: true, operationIds: {"PUT": "api_upsert_retro_experiment_outcome_v1_retrospectives__retrospective_id__experiment_outcomes_put"} },
  { pathTemplate: "/v1/state/{key}", methods: ["GET", "POST"], pathRegex: new RegExp("^/v1/state/[^/]+$"), actorRequired: true, operationIds: {"GET": "api_get_app_state_v1_state__key__get", "POST": "api_set_app_state_v1_state__key__post"} },
  { pathTemplate: "/v1/teams", methods: ["POST"], pathRegex: new RegExp("^/v1/teams$"), actorRequired: true, operationIds: {"POST": "api_create_team_v1_teams_post"} },
  { pathTemplate: "/v1/teams/{team_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/teams/\\d+$"), actorRequired: true, operationIds: {"PATCH": "api_update_team_v1_teams__team_id__patch", "DELETE": "api_delete_team_v1_teams__team_id__delete"} },
  { pathTemplate: "/v1/timer/start", methods: ["POST"], pathRegex: new RegExp("^/v1/timer/start$"), actorRequired: true, operationIds: {"POST": "api_start_timer_v1_timer_start_post"} },
  { pathTemplate: "/v1/timer/stop", methods: ["POST"], pathRegex: new RegExp("^/v1/timer/stop$"), actorRequired: true, operationIds: {"POST": "api_stop_timer_v1_timer_stop_post"} },
  { pathTemplate: "/v1/users", methods: ["POST"], pathRegex: new RegExp("^/v1/users$"), actorRequired: true, operationIds: {"POST": "api_create_user_v1_users_post"} },
  { pathTemplate: "/v1/users/{user_id}", methods: ["PATCH"], pathRegex: new RegExp("^/v1/users/\\d+$"), actorRequired: true, operationIds: {"PATCH": "api_update_user_v1_users__user_id__patch"} },
  { pathTemplate: "/v1/users/{user_id}/reset-password", methods: ["POST"], pathRegex: new RegExp("^/v1/users/\\d+/reset-password$"), actorRequired: true, operationIds: {"POST": "api_reset_user_password_v1_users__user_id__reset_password_post"} },
  { pathTemplate: "/v1/weekly-plans", methods: ["POST"], pathRegex: new RegExp("^/v1/weekly-plans$"), actorRequired: true, operationIds: {"POST": "api_create_weekly_plan_v1_weekly_plans_post"} },
  { pathTemplate: "/v1/work-logs/{work_log_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/work-logs/\\d+$"), actorRequired: true, operationIds: {"DELETE": "api_delete_work_log_v1_work_logs__work_log_id__delete"} },
];

const ACTOR_OPTIONAL_POLICY_ROUTES: readonly AllowlistRule[] = [
  { pathTemplate: "/v1/auth/login", methods: ["POST"], pathRegex: new RegExp("^/v1/auth/login$"), actorRequired: false, operationIds: {"POST": "api_auth_login_v1_auth_login_post"} },
];

function normalizeMethod(method: string): HttpMethod | null {
  const normalized = String(method || "").trim().toUpperCase();
  if (normalized === "GET" || normalized === "POST" || normalized === "PATCH" || normalized === "PUT" || normalized === "DELETE") {
    return normalized;
  }
  return null;
}

export function normalizeBackendPath(rawWildcardPath: string): string | null {
  const wildcard = String(rawWildcardPath || "").trim();
  const normalized = `/${wildcard.replace(/^\/+/, "")}`;
  if (!normalized.startsWith("/v1/")) {
    return null;
  }
  if (normalized.includes("..")) {
    return null;
  }
  if (!/^\/[a-zA-Z0-9/_-]+$/.test(normalized)) {
    return null;
  }
  return normalized;
}

export function isAllowlistedRoute(method: string, backendPath: string): boolean {
  const normalizedMethod = normalizeMethod(method);
  if (!normalizedMethod) {
    return false;
  }
  return ALLOWLIST_POLICY_ROUTES.some((rule) => {
    if (!rule.methods.includes(normalizedMethod)) {
      return false;
    }
    return rule.pathRegex.test(backendPath);
  });
}

export function resolveAllowlistedOperation(method: string, backendPath: string): BackendOperationId | null {
  const normalizedMethod = normalizeMethod(method);
  if (!normalizedMethod) {
    return null;
  }
  const rule = ALLOWLIST_POLICY_ROUTES.find((candidate) =>
    candidate.methods.includes(normalizedMethod) && candidate.pathRegex.test(backendPath),
  );
  return rule?.operationIds[normalizedMethod] ?? null;
}

export function policySignatures(): string[] {
  return ALLOWLIST_POLICY_ROUTES.flatMap((rule) =>
    rule.methods.map((method) => `${method} ${rule.pathTemplate}`),
  ).sort();
}

export function requiresActorHeader(method: string, backendPath: string): boolean {
  const normalizedMethod = normalizeMethod(method);
  if (!normalizedMethod) {
    return false;
  }
  return !ACTOR_OPTIONAL_POLICY_ROUTES.some((rule) => {
    if (!rule.methods.includes(normalizedMethod)) {
      return false;
    }
    return rule.pathRegex.test(backendPath);
  });
}
