// AUTO-GENERATED by scripts/generate_bff_allowlist.py. Do not edit by hand.
// The literal entries below are required by tooling (e.g. the backend
// mutation auth-matrix test) that parses this file with regex.

export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";

export interface AllowlistRule {
  pathTemplate: string;
  methods: readonly HttpMethod[];
  pathRegex: RegExp;
  actorRequired: boolean;
}

export const ALLOWLIST_POLICY_ROUTES: readonly AllowlistRule[] = [
  { pathTemplate: "/v1/admin/ai-health", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/ai-health$"), actorRequired: true },
  { pathTemplate: "/v1/admin/db-backup", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/db-backup$"), actorRequired: true },
  { pathTemplate: "/v1/admin/db-restore", methods: ["POST"], pathRegex: new RegExp("^/v1/admin/db-restore$"), actorRequired: true },
  { pathTemplate: "/v1/admin/pdf-health", methods: ["GET"], pathRegex: new RegExp("^/v1/admin/pdf-health$"), actorRequired: true },
  { pathTemplate: "/v1/ai/analyze-node", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/analyze-node$"), actorRequired: true },
  { pathTemplate: "/v1/ai/strategy-pulse", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/strategy-pulse$"), actorRequired: true },
  { pathTemplate: "/v1/ai/team-coach", methods: ["POST"], pathRegex: new RegExp("^/v1/ai/team-coach$"), actorRequired: true },
  { pathTemplate: "/v1/alignments", methods: ["POST"], pathRegex: new RegExp("^/v1/alignments$"), actorRequired: true },
  { pathTemplate: "/v1/alignments/{edge_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/alignments/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/auth/login", methods: ["POST"], pathRegex: new RegExp("^/v1/auth/login$"), actorRequired: false },
  { pathTemplate: "/v1/auth/me", methods: ["GET"], pathRegex: new RegExp("^/v1/auth/me$"), actorRequired: true },
  { pathTemplate: "/v1/check-ins", methods: ["POST"], pathRegex: new RegExp("^/v1/check-ins$"), actorRequired: true },
  { pathTemplate: "/v1/cycles", methods: ["POST"], pathRegex: new RegExp("^/v1/cycles$"), actorRequired: true },
  { pathTemplate: "/v1/cycles/{cycle_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/cycles/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/experiments", methods: ["POST"], pathRegex: new RegExp("^/v1/experiments$"), actorRequired: true },
  { pathTemplate: "/v1/experiments/{experiment_id}", methods: ["PATCH"], pathRegex: new RegExp("^/v1/experiments/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/experiments/{experiment_id}/close", methods: ["POST"], pathRegex: new RegExp("^/v1/experiments/\\d+/close$"), actorRequired: true },
  { pathTemplate: "/v1/jobs", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs$"), actorRequired: true },
  { pathTemplate: "/v1/jobs/dead", methods: ["GET"], pathRegex: new RegExp("^/v1/jobs/dead$"), actorRequired: true },
  { pathTemplate: "/v1/jobs/{job_id}", methods: ["GET", "DELETE"], pathRegex: new RegExp("^/v1/jobs/[^/]+$"), actorRequired: true },
  { pathTemplate: "/v1/jobs/{job_id}/cancel", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs/[^/]+/cancel$"), actorRequired: true },
  { pathTemplate: "/v1/jobs/{job_id}/retry", methods: ["POST"], pathRegex: new RegExp("^/v1/jobs/[^/]+/retry$"), actorRequired: true },
  { pathTemplate: "/v1/nodes/goal", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/goal$"), actorRequired: true },
  { pathTemplate: "/v1/nodes/key_result", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/key_result$"), actorRequired: true },
  { pathTemplate: "/v1/nodes/objective", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/objective$"), actorRequired: true },
  { pathTemplate: "/v1/nodes/task", methods: ["POST"], pathRegex: new RegExp("^/v1/nodes/task$"), actorRequired: true },
  { pathTemplate: "/v1/nodes/{node_type}/{node_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/nodes/[a-zA-Z_]+/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/objective-alignment-links", methods: ["POST"], pathRegex: new RegExp("^/v1/objective-alignment-links$"), actorRequired: true },
  { pathTemplate: "/v1/objective-alignment-links/{link_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/objective-alignment-links/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/read/atlas/snapshot", methods: ["POST"], pathRegex: new RegExp("^/v1/read/atlas/snapshot$"), actorRequired: true },
  { pathTemplate: "/v1/read/leadership/metrics", methods: ["POST"], pathRegex: new RegExp("^/v1/read/leadership/metrics$"), actorRequired: true },
  { pathTemplate: "/v1/read/query", methods: ["POST"], pathRegex: new RegExp("^/v1/read/query$"), actorRequired: true },
  { pathTemplate: "/v1/retrospectives", methods: ["POST"], pathRegex: new RegExp("^/v1/retrospectives$"), actorRequired: true },
  { pathTemplate: "/v1/retrospectives/{retrospective_id}/experiment-outcomes", methods: ["PUT"], pathRegex: new RegExp("^/v1/retrospectives/\\d+/experiment-outcomes$"), actorRequired: true },
  { pathTemplate: "/v1/state/{key}", methods: ["GET", "POST"], pathRegex: new RegExp("^/v1/state/[^/]+$"), actorRequired: true },
  { pathTemplate: "/v1/teams", methods: ["POST"], pathRegex: new RegExp("^/v1/teams$"), actorRequired: true },
  { pathTemplate: "/v1/teams/{team_id}", methods: ["PATCH", "DELETE"], pathRegex: new RegExp("^/v1/teams/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/timer/start", methods: ["POST"], pathRegex: new RegExp("^/v1/timer/start$"), actorRequired: true },
  { pathTemplate: "/v1/timer/stop", methods: ["POST"], pathRegex: new RegExp("^/v1/timer/stop$"), actorRequired: true },
  { pathTemplate: "/v1/users", methods: ["POST"], pathRegex: new RegExp("^/v1/users$"), actorRequired: true },
  { pathTemplate: "/v1/users/{user_id}", methods: ["PATCH"], pathRegex: new RegExp("^/v1/users/\\d+$"), actorRequired: true },
  { pathTemplate: "/v1/users/{user_id}/reset-password", methods: ["POST"], pathRegex: new RegExp("^/v1/users/\\d+/reset-password$"), actorRequired: true },
  { pathTemplate: "/v1/weekly-plans", methods: ["POST"], pathRegex: new RegExp("^/v1/weekly-plans$"), actorRequired: true },
  { pathTemplate: "/v1/work-logs/{work_log_id}", methods: ["DELETE"], pathRegex: new RegExp("^/v1/work-logs/\\d+$"), actorRequired: true },
];

const ACTOR_OPTIONAL_POLICY_ROUTES: readonly AllowlistRule[] = [
  { pathTemplate: "/v1/auth/login", methods: ["POST"], pathRegex: new RegExp("^/v1/auth/login$"), actorRequired: false },
];

function normalizeMethod(method: string): HttpMethod | null {
  const normalized = String(method || "").trim().toUpperCase();
  if (normalized === "GET" || normalized === "POST" || normalized === "PATCH" || normalized === "PUT" || normalized === "DELETE") {
    return normalized;
  }
  return null;
}

export function normalizeBackendPath(rawWildcardPath: string): string | null {
  const wildcard = String(rawWildcardPath || "").trim();
  const normalized = `/${wildcard.replace(/^\/+/, "")}`;
  if (!normalized.startsWith("/v1/")) {
    return null;
  }
  if (normalized.includes("..")) {
    return null;
  }
  if (!/^\/[a-zA-Z0-9/_-]+$/.test(normalized)) {
    return null;
  }
  return normalized;
}

export function isAllowlistedRoute(method: string, backendPath: string): boolean {
  const normalizedMethod = normalizeMethod(method);
  if (!normalizedMethod) {
    return false;
  }
  return ALLOWLIST_POLICY_ROUTES.some((rule) => {
    if (!rule.methods.includes(normalizedMethod)) {
      return false;
    }
    return rule.pathRegex.test(backendPath);
  });
}

export function policySignatures(): string[] {
  return ALLOWLIST_POLICY_ROUTES.flatMap((rule) =>
    rule.methods.map((method) => `${method} ${rule.pathTemplate}`),
  ).sort();
}

export function requiresActorHeader(method: string, backendPath: string): boolean {
  const normalizedMethod = normalizeMethod(method);
  if (!normalizedMethod) {
    return false;
  }
  return !ACTOR_OPTIONAL_POLICY_ROUTES.some((rule) => {
    if (!rule.methods.includes(normalizedMethod)) {
      return false;
    }
    return rule.pathRegex.test(backendPath);
  });
}
