"""Generate the SPA BFF route policy from the committed OpenAPI artifact.

Usage:
    python scripts/generate_bff_allowlist.py
    python scripts/generate_bff_allowlist.py --check
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT_DIR / "spa-web" / "src" / "lib" / "api" / "openapi.json"
POLICY_PATH = ROOT_DIR / "spa-bff" / "src" / "route-policy.json"
ALLOWLIST_PATH = ROOT_DIR / "spa-bff" / "src" / "allowlist.ts"

# These routes are present in OpenAPI but are intentionally not public BFF routes.
EXCLUDED_PATHS = {
    "/healthz",
    "/v1/admin/observability/metrics",
}

# These tighter expressions preserve existing BFF validation for enumerated path values.
PATH_PATTERN_OVERRIDES = {
    "/v1/nodes/{create_type}": r"^/v1/nodes/(goal|objective|key_result|task)$",
    "/v1/nodes/{node_type}/{node_id}": r"^/v1/nodes/[a-zA-Z_]+/\d+$",
    "/v1/jobs/{job_id}": r"^/v1/jobs/[^/]+$",
}

METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE")


def _path_regex(path_template: str) -> str:
    override = PATH_PATTERN_OVERRIDES.get(path_template)
    if override:
        return override
    def replacement(match: re.Match[str]) -> str:
        parameter = match.group(0)[1:-1]
        return r"\d+" if parameter.endswith("_id") else r"[^/]+"

    pattern = re.sub(r"\{[^}/]+\}", replacement, path_template)
    return f"^{pattern}$"


def build_policy(schema: dict, policy: dict) -> dict:
    openapi_paths = schema.get("paths", {})
    routes: list[dict] = []
    for route in policy.get("routes", []):
        path_template = route["pathTemplate"]
        if path_template in EXCLUDED_PATHS or not path_template.startswith("/v1/"):
            raise ValueError(f"BFF policy contains excluded or invalid path: {path_template}")
        path_item = openapi_paths.get(path_template)
        if path_item is None:
            raise ValueError(f"BFF policy route is missing from OpenAPI: {path_template}")
        methods = [method.upper() for method in route["methods"]]
        missing = [method for method in methods if method.lower() not in path_item]
        if missing:
            raise ValueError(f"BFF policy methods missing from OpenAPI for {path_template}: {missing}")
        routes.append(
            {
                "pathTemplate": path_template,
                "methods": methods,
                "pathPattern": _path_regex(path_template),
                "actorRequired": bool(route["actorRequired"]),
            }
        )
    return {"version": 1, "source": "spa-web/src/lib/api/openapi.json", "routes": routes}


def render_allowlist(policy: dict) -> str:
    def _rule_literal(route: dict) -> str:
        methods = ", ".join(f'"{m}"' for m in route["methods"])
        return (
            "  { pathTemplate: "
            + json.dumps(route["pathTemplate"], ensure_ascii=False)
            + ", methods: ["
            + methods
            + "], pathRegex: new RegExp("
            + json.dumps(route["pathPattern"], ensure_ascii=False)
            + "), actorRequired: "
            + ("true" if route["actorRequired"] else "false")
            + " },"
        )

    lines: list[str] = [
        "// AUTO-GENERATED by scripts/generate_bff_allowlist.py. Do not edit by hand.",
        "// The literal entries below are required by tooling (e.g. the backend",
        "// mutation auth-matrix test) that parses this file with regex.",
        "",
        'export type HttpMethod = "GET" | "POST" | "PATCH" | "PUT" | "DELETE";',
        "",
        "export interface AllowlistRule {",
        "  pathTemplate: string;",
        "  methods: readonly HttpMethod[];",
        "  pathRegex: RegExp;",
        "  actorRequired: boolean;",
        "}",
        "",
        "export const ALLOWLIST_POLICY_ROUTES: readonly AllowlistRule[] = [",
    ]
    for route in policy["routes"]:
        lines.append(_rule_literal(route))
    lines.append("];")
    lines.append("")

    actor_optional = [route for route in policy["routes"] if not route["actorRequired"]]
    lines.append("const ACTOR_OPTIONAL_POLICY_ROUTES: readonly AllowlistRule[] = [")
    for route in actor_optional:
        lines.append(_rule_literal(route))
    lines.append("];")
    lines.append("")

    lines.extend(
        [
            "function normalizeMethod(method: string): HttpMethod | null {",
            '  const normalized = String(method || "").trim().toUpperCase();',
            '  if (normalized === "GET" || normalized === "POST" || normalized === "PATCH" || normalized === "PUT" || normalized === "DELETE") {',
            "    return normalized;",
            "  }",
            "  return null;",
            "}",
            "",
            "export function normalizeBackendPath(rawWildcardPath: string): string | null {",
            '  const wildcard = String(rawWildcardPath || "").trim();',
            '  const normalized = `/${wildcard.replace(/^\\/+/, "")}`;',
            '  if (!normalized.startsWith("/v1/")) {',
            "    return null;",
            "  }",
            '  if (normalized.includes("..")) {',
            "    return null;",
            "  }",
            '  if (!/^\\/[a-zA-Z0-9/_-]+$/.test(normalized)) {',
            "    return null;",
            "  }",
            "  return normalized;",
            "}",
            "",
            "export function isAllowlistedRoute(method: string, backendPath: string): boolean {",
            "  const normalizedMethod = normalizeMethod(method);",
            "  if (!normalizedMethod) {",
            "    return false;",
            "  }",
            "  return ALLOWLIST_POLICY_ROUTES.some((rule) => {",
            "    if (!rule.methods.includes(normalizedMethod)) {",
            "      return false;",
            "    }",
            "    return rule.pathRegex.test(backendPath);",
            "  });",
            "}",
            "",
            "export function policySignatures(): string[] {",
            "  return ALLOWLIST_POLICY_ROUTES.flatMap((rule) =>",
            '    rule.methods.map((method) => `${method} ${rule.pathTemplate}`),',
            "  ).sort();",
            "}",
            "",
            "export function requiresActorHeader(method: string, backendPath: string): boolean {",
            "  const normalizedMethod = normalizeMethod(method);",
            "  if (!normalizedMethod) {",
            "    return false;",
            "  }",
            "  return !ACTOR_OPTIONAL_POLICY_ROUTES.some((rule) => {",
            "    if (!rule.methods.includes(normalizedMethod)) {",
            "      return false;",
            "    }",
            "    return rule.pathRegex.test(backendPath);",
            "  });",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def _serialized(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the SPA BFF route policy.")
    parser.add_argument("--check", action="store_true", help="Fail if generated files are stale.")
    args = parser.parse_args()

    if not OPENAPI_PATH.exists():
        print(f"[FAIL] OpenAPI artifact missing: {OPENAPI_PATH}")
        return 1
    schema = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    policy_metadata = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    policy = build_policy(schema, policy_metadata)
    expected_policy = _serialized(policy)
    expected_allowlist = render_allowlist(policy)

    stale = []
    if not ALLOWLIST_PATH.exists() or ALLOWLIST_PATH.read_text(encoding="utf-8") != expected_allowlist:
        stale.append(str(ALLOWLIST_PATH))
    if args.check:
        if stale:
            print("[FAIL] Generated BFF policy is stale:")
            print("\n".join(stale))
            print("Fix: python scripts/generate_bff_allowlist.py")
            return 1
        print(f"[PASS] BFF policy is up to date ({len(policy['routes'])} routes).")
        return 0

    ALLOWLIST_PATH.write_text(expected_allowlist, encoding="utf-8")
    print(f"BFF policy generated: {POLICY_PATH} ({len(policy['routes'])} routes)")
    print(f"BFF allowlist generated: {ALLOWLIST_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())