"""Generate the SPA operation-to-route manifest from the committed OpenAPI artifact."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = ROOT / "spa-web" / "src" / "lib" / "api" / "openapi.json"
POLICY_PATH = ROOT / "spa-bff" / "src" / "route-policy.json"
OUTPUT_PATH = (
    ROOT / "spa-web" / "src" / "lib" / "api" / "generated" / "operation-routes.ts"
)
METHODS = ("get", "post", "put", "patch", "delete")


def _parameter_types(path_item: dict, operation: dict) -> dict[str, str]:
    parameters = [
        *(path_item.get("parameters") or []),
        *(operation.get("parameters") or []),
    ]
    result: dict[str, str] = {}
    for parameter in parameters:
        if parameter.get("in") != "path":
            continue
        schema = parameter.get("schema") or {}
        enum = schema.get("enum")
        if enum:
            result[str(parameter["name"])] = " | ".join(
                json.dumps(str(value)) for value in enum
            )
        elif schema.get("type") in {"integer", "number"}:
            result[str(parameter["name"])] = "number"
        else:
            result[str(parameter["name"])] = "string"
    return result


def _typescript_path(path: str, parameter_types: dict[str, str]) -> str:
    def replace(match: re.Match[str]) -> str:
        name = match.group(1)
        return "${" + parameter_types.get(name, "string") + "}"

    return "`" + re.sub(r"\{([^}]+)\}", replace, path) + "`"


def _bff_public_operation_ids(schema: dict, policy: dict) -> set[str]:
    operation_ids: set[str] = set()
    for route in policy.get("routes", []):
        path_template = route["pathTemplate"]
        path_item = (schema.get("paths") or {}).get(path_template)
        if path_item is None:
            raise ValueError(
                f"BFF policy route is missing from OpenAPI: {path_template}"
            )
        for method in route["methods"]:
            operation = path_item.get(method.lower()) or {}
            operation_id = operation.get("operationId")
            if not operation_id:
                raise ValueError(
                    f"BFF policy method lacks an OpenAPI operation ID: "
                    f"{method} {path_template}"
                )
            operation_ids.add(str(operation_id))
    return operation_ids


def render(schema: dict, public_operation_ids: set[str] | None = None) -> str:
    entries: list[tuple[str, str, str, str]] = []
    for path, path_item in sorted((schema.get("paths") or {}).items()):
        for method in METHODS:
            operation = path_item.get(method)
            if not isinstance(operation, dict) or not operation.get("operationId"):
                continue
            operation_id = str(operation["operationId"])
            parameter_types = _parameter_types(path_item, operation)
            entries.append(
                (
                    operation_id,
                    method.upper(),
                    path,
                    _typescript_path(path, parameter_types),
                )
            )
    entries.sort()
    known_operation_ids = {operation_id for operation_id, *_rest in entries}
    if public_operation_ids is None:
        public_operation_ids = known_operation_ids
    unknown_public_operations = public_operation_ids - known_operation_ids
    if unknown_public_operations:
        raise ValueError(
            "BFF public operation IDs are absent from OpenAPI: "
            + ", ".join(sorted(unknown_public_operations))
        )
    lines = [
        "// AUTO-GENERATED by scripts/generate_spa_operation_routes.py. Do not edit by hand.",
        "",
        'export type BackendOperationMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";',
        "",
        "export const OPERATION_ROUTES = {",
    ]
    for operation_id, method, path, _type_path in entries:
        lines.append(
            f"  {json.dumps(operation_id)}: {{ method: {json.dumps(method)}, pathTemplate: {json.dumps(path)} }},"
        )
    lines.extend(["} as const;", "", "export const BFF_PUBLIC_OPERATION_IDS = ["])
    for operation_id in sorted(public_operation_ids):
        lines.append(f"  {json.dumps(operation_id)},")
    lines.extend(
        [
            "] as const;",
            "",
            "export type BffPublicOperationId = typeof BFF_PUBLIC_OPERATION_IDS[number];",
            "",
            "export interface BackendOperationPaths {",
        ]
    )
    for operation_id, _method, _path, type_path in entries:
        lines.append(f"  {json.dumps(operation_id)}: {type_path};")
    lines.extend(
        [
            "}",
            "",
            "export type BackendOperationRouteId = keyof typeof OPERATION_ROUTES;",
            "export type BackendOperationPath<Operation extends BackendOperationRouteId> = BackendOperationPaths[Operation];",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if the manifest is stale."
    )
    args = parser.parse_args()
    schema = json.loads(OPENAPI_PATH.read_text(encoding="utf-8"))
    policy = json.loads(POLICY_PATH.read_text(encoding="utf-8"))
    expected = render(schema, _bff_public_operation_ids(schema, policy))
    if args.check:
        if (
            not OUTPUT_PATH.exists()
            or OUTPUT_PATH.read_text(encoding="utf-8") != expected
        ):
            print("[FAIL] SPA operation manifest is stale.")
            print("Fix: python scripts/generate_spa_operation_routes.py")
            return 1
        print("[PASS] SPA operation manifest is up to date.")
        return 0
    OUTPUT_PATH.write_text(expected, encoding="utf-8", newline="\n")
    print(f"SPA operation manifest generated: {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
