{
    'name': 'OKR Tracker',
    'version': '1.0',
    'category': 'Productivity',
    'summary': 'Manage Objectives and Key Results (OKR)',
    'description': 'Simplified OKR module focused on Objectives and Key Results. Work items (initiatives/tasks) should be managed in the Project module and linked via the Project field.',
    'author': 'Your Name',
    'depends': ['base','project'],
    'data': [
        'security/okr_security.xml',
        'security/ir.model.access.csv',
        'views/okr_views.xml',
        'views/wizard_migration.xml',
        'views/actions.xml',
        'views/migration_log_views.xml',
        'views/okr_menus.xml',
        'views/wizard_preview.xml',
        'views/wizard_rollback_confirm.xml',
    ],
    'installable': True,
    'application': True,
}